/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2022-04-27 22:25:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import entity.Product;
import java.util.TreeMap;
import entity.Cart;

public final class Cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1650952988694L));
    _jspx_dependants.put("jar:file:/D:/BaoCao/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shop/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entity.Product");
    _jspx_imports_classes.add("java.util.TreeMap");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("entity.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("       <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Menu.jsp", out, false);
      out.write("\n");
      out.write("    ");

    Cart cart = (Cart)session.getAttribute("cart");
    if(cart == null){
    	cart = new Cart();
    	session.setAttribute("cart", cart);
    }
    TreeMap<Product,Integer> list = cart.getList();
    
      out.write("\n");
      out.write("      \n");
      out.write("        <div class=\"shopping-cart\">\n");
      out.write("            <div class=\"px-4 px-lg-0\">\n");
      out.write("\n");
      out.write("                <div class=\"pb-5\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-lg-12 p-5 bg-white rounded shadow-sm mb-5\">\n");
      out.write("\n");
      out.write("                                <!-- Shopping cart table -->\n");
      out.write("                                <div class=\"table-responsive\">\n");
      out.write("                                    <table class=\"table\">\n");
      out.write("                                        <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th scope=\"col\" class=\"border-0 bg-light\">\n");
      out.write("                                                    <div class=\"p-2 px-3 text-uppercase\">Sản Phẩm</div>\n");
      out.write("                                                </th>\n");
      out.write("                                                <th scope=\"col\" class=\"border-0 bg-light\">\n");
      out.write("                                                    <div class=\"py-2 text-uppercase\">Đơn Giá</div>\n");
      out.write("                                                </th>\n");
      out.write("                                                <th scope=\"col\" class=\"border-0 bg-light\">\n");
      out.write("                                                    <div class=\"py-2 text-uppercase\">Số Lượng</div>\n");
      out.write("                                                </th>\n");
      out.write("                                                <th scope=\"col\" class=\"border-0 bg-light\">\n");
      out.write("                                                    <div class=\"py-2 text-uppercase\">Thanh toán</div>\n");
      out.write("                                                </th>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </thead>\n");
      out.write("                                        <tbody>\n");
      out.write("                                       ");
 for(Map.Entry<Product,Integer> ds : list.entrySet()){
                                       
      out.write("\n");
      out.write("                                            \n");
      out.write("                                                <tr>\n");
      out.write("                                                    <th scope=\"row\">\n");
      out.write("                                                        <div class=\"p-2\">\n");
      out.write("                                                            <img src=\"");
      out.print(ds.getKey().getImage() );
      out.write("\" alt=\"\" width=\"70\" class=\"img-fluid rounded shadow-sm\">\n");
      out.write("                                                            <div class=\"ml-3 d-inline-block align-middle\">\n");
      out.write("                                                                <h5 class=\"mb-0\"> <a href=\"#\" class=\"text-dark d-inline-block\">");
      out.print(ds.getKey().getName() );
      out.write("</a></h5><span class=\"text-muted font-weight-normal font-italic\"></span>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </th>\n");
      out.write("                                                    <td class=\"align-middle\"><strong>");
      out.print(ds.getKey().getPrice() );
      out.write("</strong></td>\n");
      out.write("                                                    <td class=\"align-middle\">\n");
      out.write("                                                        <a href=\"CartControl?command=sub&maSanPham=");
      out.print(ds.getKey().getId());
      out.write("&cartID=");
      out.print(System.currentTimeMillis() );
      out.write("\">\n");
      out.write("                                                        <button class=\"btnSub\">-</button></a> \n");
      out.write("                                                        <strong>");
      out.print(ds.getValue());
      out.write("</strong>\n");
      out.write("                                                        <a href=\"CartControl?command=plus&maSanPham=");
      out.print(ds.getKey().getId());
      out.write("&cartID=");
      out.print(System.currentTimeMillis() );
      out.write("\"><button class=\"btnAdd\">+</button></a>\n");
      out.write("                                                    </td>\n");
      out.write("                                                    \n");
      out.write("                                                        <td class=\"cart_total\">\n");
      out.write("                                                        <p class=\"cart_total_price\">");
      out.print(ds.getValue()*ds.getKey().getPrice() );
      out.write("\n");
      out.write("                                                           \n");
      out.write("                                                    \n");
      out.write("                                                    </td>\n");
      out.write("                                                </tr> \n");
      out.write("                                         \n");
      out.write("                                        ");
} 
      out.write("\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- End -->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"row py-5 p-4 bg-white rounded shadow-sm\">\n");
      out.write("                           \n");
      out.write("               \n");
      out.write("                                    <ul class=\"list-unstyled mb-4\">\n");
      out.write("                                       \n");
      out.write("                                    \n");
      out.write("                                    </ul><a href=\"DatHang.jsp\" class=\"btn btn-dark rounded-pill py-2 btn-block\">Mua hàng</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write(" \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("         \n");
      out.write("      \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
